services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $centrifugoChannelMaxLength: '%centrifugo.channel_max_length%'
            $centrifugoJwtTtl: '%centrifugo.jwt.ttl%'
            $centrifugoSecret: '%env(CENTRIFUGO_SECRET)%'
            iterable $channelAuthenticators: !tagged_iterator 'centrifugo.channel_authenticator'

    Fresh\CentrifugoBundle\:
        resource: '../../{Command,Logger,Service}/'
        exclude: '../../Service/Centrifugo.php'

    Fresh\CentrifugoBundle\DataCollector\CentrifugoCollector:
        tags:
            -
                id: 'centrifugo'
                name: data_collector
                template: '@FreshCentrifugo/data_collector/centrifugo.html.twig'

    Fresh\CentrifugoBundle\Service\ResponseProcessor:
        class: Fresh\CentrifugoBundle\Service\ResponseProcessor
        arguments:
            - '@Fresh\CentrifugoBundle\Service\CentrifugoChecker'
            - '@Fresh\CentrifugoBundle\Logger\CommandHistoryLogger'
            - '@?profiler'
