services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $centrifugoChannelMaxLength: '%centrifugo.channel_max_length%'
            $centrifugoJwtAlgorithm: '%centrifugo.jwt.algorithm%'
            $centrifugoJwtTtl: '%centrifugo.jwt.ttl%'
            $centrifugoSecret: '%env(CENTRIFUGO_SECRET)%'
            iterable $channelAuthenticators: !tagged_iterator 'centrifugo.channel_authenticator'

    Fresh\CentrifugoBundle\:
        resource: '../../{Command,Logger,Service}/'

    Fresh\CentrifugoBundle\Service\Centrifugo:
        class: Fresh\CentrifugoBundle\Service\Centrifugo
        arguments:
            - '%env(CENTRIFUGO_API_ENDPOINT)%'
            - '%env(CENTRIFUGO_API_KEY)%'
            - '@http_client'
            - '@Fresh\CentrifugoBundle\Service\ResponseProcessor'
            - '@Fresh\CentrifugoBundle\Logger\CommandHistoryLogger'
            - '@Fresh\CentrifugoBundle\Service\CentrifugoChecker'
            - '@?profiler'
