services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $centrifugoChannelMaxLength: '%centrifugo.channel_max_length%'

    Fresh\CentrifugoBundle\:
        resource: '../../{Command,Logger,Service}/'

    Fresh\CentrifugoBundle\DataCollector\CentrifugoCollector:
        tags:
            -
                id: 'centrifugo'
                name: data_collector
                template: '@FreshCentrifugo/data_collector/centrifugo.html.twig'

    Fresh\CentrifugoBundle\Service\Centrifugo:
        class: Fresh\CentrifugoBundle\Service\Centrifugo
        arguments:
            - '%env(APP_CENTRIFUGO_API_ENDPOINT)%'
            - '%env(APP_CENTRIFUGO_API_KEY)%'
            - '%env(APP_CENTRIFUGO_SECRET)%'
            - '@http_client'
            - '@Fresh\CentrifugoBundle\Service\ResponseProcessor'
            - '@Fresh\CentrifugoBundle\Logger\CommandHistoryLogger'
            - '@Fresh\CentrifugoBundle\Service\CentrifugoChecker'
            - '@?profiler'
